The purpose of this r-markdown is to set up a program to run the r package "POWSC," created by Wu et al.


Install Software:
```{r message=FALSE}
install.packages("RCurl")
setRepositories(ind = 1:5)
install.packages(c("Biobase", "limma", "SingleCellExperiment", "MAST", "SummarizedExperiment"))

library(devtools)

install_github("haowulab/SC2P", build_vignettes=T)
install_github("suke18/POWSC", build_vignettes = T, dependencies = T)
```
**Note: SC2P is a package also create by the Wu Lab. It's purpose is to test DE for single cell RNA-seq data.


Estimation for a single cell type
```{r}
library(POWSC)
data("es_mef_sce")
sce = es_mef_sce[, colData(es_mef_sce)$cellTypes == "fibro"]
est_Paras = Est2Phase(sce)
```

Simulate data set and plot for two group comparison 
```{r}
sim_size = c(100, 400, 1000) # A numeric vector
pow_rslt = runPOWSC(sim_size = sim_size, est_Paras = est_Paras,per_DE=0.05, DE_Method = "MAST", Cell_Type = "PW") # Note, using our previous developed tool SC2P is faster.
plot(pow_rslt, Form="II", Cell_Type = "PW") # Alternatively, we can use Form="I"
summary(pow_rslt, Form="II", Cell_Type = "PW")
```


Simulate data for multi-group comparison
```{r}
sim_size = 1000
cell_per = c(0.2, 0.3, 0.5)
data("GSE67835")
col = colData(sce)
exprs = assays(sce)$counts
(tb = table(colData(sce)$Patients, colData(sce)$cellTypes))
# use AB_S7 patient as example and take three cell types: astrocytes hybrid and neurons
estParas_set = NULL
celltypes = c("oligodendrocytes", "hybrid", "neurons")
for (cp in celltypes){
    print(cp)
    ix = intersect(grep(cp, col$cellTypes), grep("AB_S7", col$Patients))
    tmp_mat = exprs[, ix]
    tmp_paras = Est2Phase(tmp_mat)
    estParas_set[[cp]] = tmp_paras
}
pow_rslt = runPOWSC(sim_size = sim_size, est_Paras = estParas_set,per_DE=0.05, DE_Method = "MAST",multi_Prob = cell_per, Cell_Type = "Multi")
plot(pow_rslt, Form="I", Cell_Type = "Multi")
summary(pow_rslt, Form="II", Cell_Type = "Multi")


```

